name: devotional_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  google_sign_in: ^7.1.1

  # Core Flutter
  cupertino_icons: ^1.0.8

  # UI and Formatting
  flutter_screenutil: ^5.9.3
  intl: ^0.20.2
  carousel_slider: ^5.1.1

  # Storage and Database
  path_provider: ^2.1.5
  sqflite: ^2.4.2
  path: ^1.9.1
  shared_preferences: ^2.5.3

  # Backend
  supabase_flutter: ^2.9.1
  http: ^1.2.2

  # Connectivity and Permissions
  connectivity_plus: ^6.1.4
  permission_handler: ^12.0.1

  # Notifications
  flutter_local_notifications: ^19.4.0
  timezone: ^0.10.1

  flutter_datetime_picker: ^1.5.1
  image_picker: ^1.0.4
  device_preview: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1 # Add this

flutter:
  uses-material-design: true
  assets:
    - shorebird.yaml
    - assets/images/iiii.png # For login page
    - assets/images/iiii - Copy.png # For launcher icon (optional if using same image)
    - assets/images/birthday_cake.png #For birthday

# Launcher icon configuration
flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/iiii - Copy.png"
  # Optionally customize Android icon shape:
  # adaptive_icon_background: "#ffffff"
  # adaptive_icon_foreground: "assets/images/app_icon_foreground.png"
